/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AppClientes { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idcliente?: string;
    nombre?: string;
    telefono?: string;
    descripcion?: string;
    imagen?: string;
    ruc?: string;
    password?: string;
    /**
     * Note: This is a Foreign Key to `app_users.iduser`.<fk table='app_users' column='iduser'/>
     */
    usercreate?: string;
    fecharegistro?: string;
}
