/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AppDmarcaciones { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idmarcacion: number;
    /**
     * Note: This is a Foreign Key to `app_drivers.iddriver`.<fk table='app_drivers' column='iddriver'/>
     */
    iddriver?: string;
    entrada?: string;
    salida?: string;
    fecharegistro?: string;
}
