/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AppDrivers { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    iddriver: string;
    nombre?: string;
    direccion?: string;
    imagen1?: string;
    imagen2?: string;
    imagen3?: string;
    telefono?: string;
    /**
     * Note: This is a Foreign Key to `app_estado.idestado`.<fk table='app_estado' column='idestado'/>
     */
    idestado?: number;
    /**
     * estado de servicio, llevando recogiendo, libre etc
     */
    idestadoservicio?: number;
    /**
     * Note: This is a Foreign Key to `app_unidad.idunidad`.<fk table='app_unidad' column='idunidad'/>
     */
    idunidad?: string;
    unidadplaca?: string;
    unidadcolor?: string;
    fecharegistro?: string;
}
