/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AppServicios { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idservicio?: number;
    /**
     * Note: This is a Foreign Key to `app_cliente_locales.idcliente`.<fk table='app_cliente_locales' column='idcliente'/>
     */
    idcliente?: number;
    /**
     * Note: This is a Foreign Key to `app_cliente_locales.idlocal`.<fk table='app_cliente_locales' column='idlocal'/>
     */
    idlocal?: number;
    /**
     * Note: This is a Foreign Key to `app_estado.idestado`.<fk table='app_estado' column='idestado'/>
     */
    idestado?: number;
    /**
     * Note: This is a Foreign Key to `app_cfinal.idcfinal`.<fk table='app_cfinal' column='idcfinal'/>
     */
    idcfinal?: string;
    /**
     * Note: This is a Foreign Key to `app_drivers.iddriver`.<fk table='app_drivers' column='iddriver'/>
     */
    iddriver?: string;
    destinolat?: string;
    destinolng?: string;
    tiempoval?: string;
    tiempotext?: string;
    distancia?: number;
    fechahorainicio?: string;
    fechahorallegada?: string;
    clientevaloracion?: number;
    clientecomentario?: string;
    drivervaloracion?: number;
    drivercomentario?: string;
    notificado?: boolean;
    costoentrega?: number;
    costototal?: number;
    /**
     * Note: This is a Foreign Key to `app_metodopago.idmetodopago`.<fk table='app_metodopago' column='idmetodopago'/>
     */
    metodopago?: string;
    fecharegistro?: string;
}
