export * from './appCfinal.service';
import { AppCfinalService } from './appCfinal.service';
export * from './appClienteLocales.service';
import { AppClienteLocalesService } from './appClienteLocales.service';
export * from './appClientes.service';
import { AppClientesService } from './appClientes.service';
export * from './appDmarcaciones.service';
import { AppDmarcacionesService } from './appDmarcaciones.service';
export * from './appDrivers.service';
import { AppDriversService } from './appDrivers.service';
export * from './appEstado.service';
import { AppEstadoService } from './appEstado.service';
export * from './appMetodopago.service';
import { AppMetodopagoService } from './appMetodopago.service';
export * from './appServicios.service';
import { AppServiciosService } from './appServicios.service';
export * from './appUnidad.service';
import { AppUnidadService } from './appUnidad.service';
export * from './appUsers.service';
import { AppUsersService } from './appUsers.service';
export * from './introspection.service';
import { IntrospectionService } from './introspection.service';
export * from './viewClientesFrecuentes.service';
import { ViewClientesFrecuentesService } from './viewClientesFrecuentes.service';
export const APIS = [AppCfinalService, AppClienteLocalesService, AppClientesService, AppDmarcacionesService, AppDriversService, AppEstadoService, AppMetodopagoService, AppServiciosService, AppUnidadService, AppUsersService, IntrospectionService, ViewClientesFrecuentesService];
