/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AppDrivers } from '../model/appDrivers';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AppDriversService {

    protected basePath = 'http://app.mandala.red:3002';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param iddriver 
     * @param nombre 
     * @param direccion 
     * @param imagen1 
     * @param imagen2 
     * @param imagen3 
     * @param telefono 
     * @param idestado 
     * @param idestadoservicio estado de servicio, llevando recogiendo, libre etc
     * @param idunidad 
     * @param unidadplaca 
     * @param unidadcolor 
     * @param fecharegistro 
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appDriversDelete(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appDriversDelete(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appDriversDelete(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appDriversDelete(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (iddriver !== undefined && iddriver !== null) {
            queryParameters = queryParameters.set('iddriver', <any>iddriver);
        }
        if (nombre !== undefined && nombre !== null) {
            queryParameters = queryParameters.set('nombre', <any>nombre);
        }
        if (direccion !== undefined && direccion !== null) {
            queryParameters = queryParameters.set('direccion', <any>direccion);
        }
        if (imagen1 !== undefined && imagen1 !== null) {
            queryParameters = queryParameters.set('imagen1', <any>imagen1);
        }
        if (imagen2 !== undefined && imagen2 !== null) {
            queryParameters = queryParameters.set('imagen2', <any>imagen2);
        }
        if (imagen3 !== undefined && imagen3 !== null) {
            queryParameters = queryParameters.set('imagen3', <any>imagen3);
        }
        if (telefono !== undefined && telefono !== null) {
            queryParameters = queryParameters.set('telefono', <any>telefono);
        }
        if (idestado !== undefined && idestado !== null) {
            queryParameters = queryParameters.set('idestado', <any>idestado);
        }
        if (idestadoservicio !== undefined && idestadoservicio !== null) {
            queryParameters = queryParameters.set('idestadoservicio', <any>idestadoservicio);
        }
        if (idunidad !== undefined && idunidad !== null) {
            queryParameters = queryParameters.set('idunidad', <any>idunidad);
        }
        if (unidadplaca !== undefined && unidadplaca !== null) {
            queryParameters = queryParameters.set('unidadplaca', <any>unidadplaca);
        }
        if (unidadcolor !== undefined && unidadcolor !== null) {
            queryParameters = queryParameters.set('unidadcolor', <any>unidadcolor);
        }
        if (fecharegistro !== undefined && fecharegistro !== null) {
            queryParameters = queryParameters.set('fecharegistro', <any>fecharegistro);
        }

        let headers = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/app_drivers`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param iddriver 
     * @param nombre 
     * @param direccion 
     * @param imagen1 
     * @param imagen2 
     * @param imagen3 
     * @param telefono 
     * @param idestado 
     * @param idestadoservicio estado de servicio, llevando recogiendo, libre etc
     * @param idunidad 
     * @param unidadplaca 
     * @param unidadcolor 
     * @param fecharegistro 
     * @param select Filtering Columns
     * @param order Ordering
     * @param range Limiting and Pagination
     * @param rangeUnit Limiting and Pagination
     * @param offset Limiting and Pagination
     * @param limit Limiting and Pagination
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appDriversGet(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'body', reportProgress?: boolean): Observable<Array<AppDrivers>>;
    public appDriversGet(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AppDrivers>>>;
    public appDriversGet(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AppDrivers>>>;
    public appDriversGet(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (iddriver !== undefined && iddriver !== null) {
            queryParameters = queryParameters.set('iddriver', <any>iddriver);
        }
        if (nombre !== undefined && nombre !== null) {
            queryParameters = queryParameters.set('nombre', <any>nombre);
        }
        if (direccion !== undefined && direccion !== null) {
            queryParameters = queryParameters.set('direccion', <any>direccion);
        }
        if (imagen1 !== undefined && imagen1 !== null) {
            queryParameters = queryParameters.set('imagen1', <any>imagen1);
        }
        if (imagen2 !== undefined && imagen2 !== null) {
            queryParameters = queryParameters.set('imagen2', <any>imagen2);
        }
        if (imagen3 !== undefined && imagen3 !== null) {
            queryParameters = queryParameters.set('imagen3', <any>imagen3);
        }
        if (telefono !== undefined && telefono !== null) {
            queryParameters = queryParameters.set('telefono', <any>telefono);
        }
        if (idestado !== undefined && idestado !== null) {
            queryParameters = queryParameters.set('idestado', <any>idestado);
        }
        if (idestadoservicio !== undefined && idestadoservicio !== null) {
            queryParameters = queryParameters.set('idestadoservicio', <any>idestadoservicio);
        }
        if (idunidad !== undefined && idunidad !== null) {
            queryParameters = queryParameters.set('idunidad', <any>idunidad);
        }
        if (unidadplaca !== undefined && unidadplaca !== null) {
            queryParameters = queryParameters.set('unidadplaca', <any>unidadplaca);
        }
        if (unidadcolor !== undefined && unidadcolor !== null) {
            queryParameters = queryParameters.set('unidadcolor', <any>unidadcolor);
        }
        if (fecharegistro !== undefined && fecharegistro !== null) {
            queryParameters = queryParameters.set('fecharegistro', <any>fecharegistro);
        }
        if (select !== undefined && select !== null) {
            queryParameters = queryParameters.set('select', <any>select);
        }
        if (order !== undefined && order !== null) {
            queryParameters = queryParameters.set('order', <any>order);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;
        if (range !== undefined && range !== null) {
            headers = headers.set('Range', String(range));
        }
        if (rangeUnit !== undefined && rangeUnit !== null) {
            headers = headers.set('Range-Unit', String(rangeUnit));
        }
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];

        return this.httpClient.get<Array<AppDrivers>>(`${this.basePath}/app_drivers`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param iddriver 
     * @param nombre 
     * @param direccion 
     * @param imagen1 
     * @param imagen2 
     * @param imagen3 
     * @param telefono 
     * @param idestado 
     * @param idestadoservicio estado de servicio, llevando recogiendo, libre etc
     * @param idunidad 
     * @param unidadplaca 
     * @param unidadcolor 
     * @param fecharegistro 
     * @param appDrivers app_drivers
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appDriversPatch(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, appDrivers?: AppDrivers, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appDriversPatch(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, appDrivers?: AppDrivers, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appDriversPatch(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, appDrivers?: AppDrivers, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appDriversPatch(iddriver?: string, nombre?: string, direccion?: string, imagen1?: string, imagen2?: string, imagen3?: string, telefono?: string, idestado?: string, idestadoservicio?: string, idunidad?: string, unidadplaca?: string, unidadcolor?: string, fecharegistro?: string, appDrivers?: AppDrivers, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (iddriver !== undefined && iddriver !== null) {
            queryParameters = queryParameters.set('iddriver', <any>iddriver);
        }
        if (nombre !== undefined && nombre !== null) {
            queryParameters = queryParameters.set('nombre', <any>nombre);
        }
        if (direccion !== undefined && direccion !== null) {
            queryParameters = queryParameters.set('direccion', <any>direccion);
        }
        if (imagen1 !== undefined && imagen1 !== null) {
            queryParameters = queryParameters.set('imagen1', <any>imagen1);
        }
        if (imagen2 !== undefined && imagen2 !== null) {
            queryParameters = queryParameters.set('imagen2', <any>imagen2);
        }
        if (imagen3 !== undefined && imagen3 !== null) {
            queryParameters = queryParameters.set('imagen3', <any>imagen3);
        }
        if (telefono !== undefined && telefono !== null) {
            queryParameters = queryParameters.set('telefono', <any>telefono);
        }
        if (idestado !== undefined && idestado !== null) {
            queryParameters = queryParameters.set('idestado', <any>idestado);
        }
        if (idestadoservicio !== undefined && idestadoservicio !== null) {
            queryParameters = queryParameters.set('idestadoservicio', <any>idestadoservicio);
        }
        if (idunidad !== undefined && idunidad !== null) {
            queryParameters = queryParameters.set('idunidad', <any>idunidad);
        }
        if (unidadplaca !== undefined && unidadplaca !== null) {
            queryParameters = queryParameters.set('unidadplaca', <any>unidadplaca);
        }
        if (unidadcolor !== undefined && unidadcolor !== null) {
            queryParameters = queryParameters.set('unidadcolor', <any>unidadcolor);
        }
        if (fecharegistro !== undefined && fecharegistro !== null) {
            queryParameters = queryParameters.set('fecharegistro', <any>fecharegistro);
        }

        let headers = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<any>(`${this.basePath}/app_drivers`,
            appDrivers,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param appDrivers app_drivers
     * @param select Filtering Columns
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appDriversPost(appDrivers?: AppDrivers, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appDriversPost(appDrivers?: AppDrivers, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appDriversPost(appDrivers?: AppDrivers, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appDriversPost(appDrivers?: AppDrivers, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (select !== undefined && select !== null) {
            queryParameters = queryParameters.set('select', <any>select);
        }

        let headers = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/app_drivers`,
            appDrivers,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
