/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AppServicios } from '../model/appServicios';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AppServiciosService {

    protected basePath = 'http://app.mandala.red:3002';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param idservicio 
     * @param idcliente 
     * @param idlocal 
     * @param idestado 
     * @param idcfinal 
     * @param iddriver 
     * @param destinolat 
     * @param destinolng 
     * @param tiempoval 
     * @param tiempotext 
     * @param distancia 
     * @param fechahorainicio 
     * @param fechahorallegada 
     * @param clientevaloracion 
     * @param clientecomentario 
     * @param drivervaloracion 
     * @param drivercomentario 
     * @param notificado 
     * @param costoentrega 
     * @param costototal 
     * @param metodopago 
     * @param fecharegistro 
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appServiciosDelete(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appServiciosDelete(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appServiciosDelete(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appServiciosDelete(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
























        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idservicio !== undefined && idservicio !== null) {
            queryParameters = queryParameters.set('idservicio', <any>idservicio);
        }
        if (idcliente !== undefined && idcliente !== null) {
            queryParameters = queryParameters.set('idcliente', <any>idcliente);
        }
        if (idlocal !== undefined && idlocal !== null) {
            queryParameters = queryParameters.set('idlocal', <any>idlocal);
        }
        if (idestado !== undefined && idestado !== null) {
            queryParameters = queryParameters.set('idestado', <any>idestado);
        }
        if (idcfinal !== undefined && idcfinal !== null) {
            queryParameters = queryParameters.set('idcfinal', <any>idcfinal);
        }
        if (iddriver !== undefined && iddriver !== null) {
            queryParameters = queryParameters.set('iddriver', <any>iddriver);
        }
        if (destinolat !== undefined && destinolat !== null) {
            queryParameters = queryParameters.set('destinolat', <any>destinolat);
        }
        if (destinolng !== undefined && destinolng !== null) {
            queryParameters = queryParameters.set('destinolng', <any>destinolng);
        }
        if (tiempoval !== undefined && tiempoval !== null) {
            queryParameters = queryParameters.set('tiempoval', <any>tiempoval);
        }
        if (tiempotext !== undefined && tiempotext !== null) {
            queryParameters = queryParameters.set('tiempotext', <any>tiempotext);
        }
        if (distancia !== undefined && distancia !== null) {
            queryParameters = queryParameters.set('distancia', <any>distancia);
        }
        if (fechahorainicio !== undefined && fechahorainicio !== null) {
            queryParameters = queryParameters.set('fechahorainicio', <any>fechahorainicio);
        }
        if (fechahorallegada !== undefined && fechahorallegada !== null) {
            queryParameters = queryParameters.set('fechahorallegada', <any>fechahorallegada);
        }
        if (clientevaloracion !== undefined && clientevaloracion !== null) {
            queryParameters = queryParameters.set('clientevaloracion', <any>clientevaloracion);
        }
        if (clientecomentario !== undefined && clientecomentario !== null) {
            queryParameters = queryParameters.set('clientecomentario', <any>clientecomentario);
        }
        if (drivervaloracion !== undefined && drivervaloracion !== null) {
            queryParameters = queryParameters.set('drivervaloracion', <any>drivervaloracion);
        }
        if (drivercomentario !== undefined && drivercomentario !== null) {
            queryParameters = queryParameters.set('drivercomentario', <any>drivercomentario);
        }
        if (notificado !== undefined && notificado !== null) {
            queryParameters = queryParameters.set('notificado', <any>notificado);
        }
        if (costoentrega !== undefined && costoentrega !== null) {
            queryParameters = queryParameters.set('costoentrega', <any>costoentrega);
        }
        if (costototal !== undefined && costototal !== null) {
            queryParameters = queryParameters.set('costototal', <any>costototal);
        }
        if (metodopago !== undefined && metodopago !== null) {
            queryParameters = queryParameters.set('metodopago', <any>metodopago);
        }
        if (fecharegistro !== undefined && fecharegistro !== null) {
            queryParameters = queryParameters.set('fecharegistro', <any>fecharegistro);
        }

        let headers = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/app_servicios`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param idservicio 
     * @param idcliente 
     * @param idlocal 
     * @param idestado 
     * @param idcfinal 
     * @param iddriver 
     * @param destinolat 
     * @param destinolng 
     * @param tiempoval 
     * @param tiempotext 
     * @param distancia 
     * @param fechahorainicio 
     * @param fechahorallegada 
     * @param clientevaloracion 
     * @param clientecomentario 
     * @param drivervaloracion 
     * @param drivercomentario 
     * @param notificado 
     * @param costoentrega 
     * @param costototal 
     * @param metodopago 
     * @param fecharegistro 
     * @param select Filtering Columns
     * @param order Ordering
     * @param range Limiting and Pagination
     * @param rangeUnit Limiting and Pagination
     * @param offset Limiting and Pagination
     * @param limit Limiting and Pagination
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appServiciosGet(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'body', reportProgress?: boolean): Observable<Array<AppServicios>>;
    public appServiciosGet(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AppServicios>>>;
    public appServiciosGet(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AppServicios>>>;
    public appServiciosGet(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






























        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idservicio !== undefined && idservicio !== null) {
            queryParameters = queryParameters.set('idservicio', <any>idservicio);
        }
        if (idcliente !== undefined && idcliente !== null) {
            queryParameters = queryParameters.set('idcliente', <any>idcliente);
        }
        if (idlocal !== undefined && idlocal !== null) {
            queryParameters = queryParameters.set('idlocal', <any>idlocal);
        }
        if (idestado !== undefined && idestado !== null) {
            queryParameters = queryParameters.set('idestado', <any>idestado);
        }
        if (idcfinal !== undefined && idcfinal !== null) {
            queryParameters = queryParameters.set('idcfinal', <any>idcfinal);
        }
        if (iddriver !== undefined && iddriver !== null) {
            queryParameters = queryParameters.set('iddriver', <any>iddriver);
        }
        if (destinolat !== undefined && destinolat !== null) {
            queryParameters = queryParameters.set('destinolat', <any>destinolat);
        }
        if (destinolng !== undefined && destinolng !== null) {
            queryParameters = queryParameters.set('destinolng', <any>destinolng);
        }
        if (tiempoval !== undefined && tiempoval !== null) {
            queryParameters = queryParameters.set('tiempoval', <any>tiempoval);
        }
        if (tiempotext !== undefined && tiempotext !== null) {
            queryParameters = queryParameters.set('tiempotext', <any>tiempotext);
        }
        if (distancia !== undefined && distancia !== null) {
            queryParameters = queryParameters.set('distancia', <any>distancia);
        }
        if (fechahorainicio !== undefined && fechahorainicio !== null) {
            queryParameters = queryParameters.set('fechahorainicio', <any>fechahorainicio);
        }
        if (fechahorallegada !== undefined && fechahorallegada !== null) {
            queryParameters = queryParameters.set('fechahorallegada', <any>fechahorallegada);
        }
        if (clientevaloracion !== undefined && clientevaloracion !== null) {
            queryParameters = queryParameters.set('clientevaloracion', <any>clientevaloracion);
        }
        if (clientecomentario !== undefined && clientecomentario !== null) {
            queryParameters = queryParameters.set('clientecomentario', <any>clientecomentario);
        }
        if (drivervaloracion !== undefined && drivervaloracion !== null) {
            queryParameters = queryParameters.set('drivervaloracion', <any>drivervaloracion);
        }
        if (drivercomentario !== undefined && drivercomentario !== null) {
            queryParameters = queryParameters.set('drivercomentario', <any>drivercomentario);
        }
        if (notificado !== undefined && notificado !== null) {
            queryParameters = queryParameters.set('notificado', <any>notificado);
        }
        if (costoentrega !== undefined && costoentrega !== null) {
            queryParameters = queryParameters.set('costoentrega', <any>costoentrega);
        }
        if (costototal !== undefined && costototal !== null) {
            queryParameters = queryParameters.set('costototal', <any>costototal);
        }
        if (metodopago !== undefined && metodopago !== null) {
            queryParameters = queryParameters.set('metodopago', <any>metodopago);
        }
        if (fecharegistro !== undefined && fecharegistro !== null) {
            queryParameters = queryParameters.set('fecharegistro', <any>fecharegistro);
        }
        if (select !== undefined && select !== null) {
            queryParameters = queryParameters.set('select', <any>select);
        }
        if (order !== undefined && order !== null) {
            queryParameters = queryParameters.set('order', <any>order);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;
        if (range !== undefined && range !== null) {
            headers = headers.set('Range', String(range));
        }
        if (rangeUnit !== undefined && rangeUnit !== null) {
            headers = headers.set('Range-Unit', String(rangeUnit));
        }
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];

        return this.httpClient.get<Array<AppServicios>>(`${this.basePath}/app_servicios`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param idservicio 
     * @param idcliente 
     * @param idlocal 
     * @param idestado 
     * @param idcfinal 
     * @param iddriver 
     * @param destinolat 
     * @param destinolng 
     * @param tiempoval 
     * @param tiempotext 
     * @param distancia 
     * @param fechahorainicio 
     * @param fechahorallegada 
     * @param clientevaloracion 
     * @param clientecomentario 
     * @param drivervaloracion 
     * @param drivercomentario 
     * @param notificado 
     * @param costoentrega 
     * @param costototal 
     * @param metodopago 
     * @param fecharegistro 
     * @param appServicios app_servicios
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appServiciosPatch(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, appServicios?: AppServicios, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appServiciosPatch(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, appServicios?: AppServicios, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appServiciosPatch(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, appServicios?: AppServicios, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appServiciosPatch(idservicio?: string, idcliente?: string, idlocal?: string, idestado?: string, idcfinal?: string, iddriver?: string, destinolat?: string, destinolng?: string, tiempoval?: string, tiempotext?: string, distancia?: string, fechahorainicio?: string, fechahorallegada?: string, clientevaloracion?: string, clientecomentario?: string, drivervaloracion?: string, drivercomentario?: string, notificado?: string, costoentrega?: string, costototal?: string, metodopago?: string, fecharegistro?: string, appServicios?: AppServicios, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

























        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idservicio !== undefined && idservicio !== null) {
            queryParameters = queryParameters.set('idservicio', <any>idservicio);
        }
        if (idcliente !== undefined && idcliente !== null) {
            queryParameters = queryParameters.set('idcliente', <any>idcliente);
        }
        if (idlocal !== undefined && idlocal !== null) {
            queryParameters = queryParameters.set('idlocal', <any>idlocal);
        }
        if (idestado !== undefined && idestado !== null) {
            queryParameters = queryParameters.set('idestado', <any>idestado);
        }
        if (idcfinal !== undefined && idcfinal !== null) {
            queryParameters = queryParameters.set('idcfinal', <any>idcfinal);
        }
        if (iddriver !== undefined && iddriver !== null) {
            queryParameters = queryParameters.set('iddriver', <any>iddriver);
        }
        if (destinolat !== undefined && destinolat !== null) {
            queryParameters = queryParameters.set('destinolat', <any>destinolat);
        }
        if (destinolng !== undefined && destinolng !== null) {
            queryParameters = queryParameters.set('destinolng', <any>destinolng);
        }
        if (tiempoval !== undefined && tiempoval !== null) {
            queryParameters = queryParameters.set('tiempoval', <any>tiempoval);
        }
        if (tiempotext !== undefined && tiempotext !== null) {
            queryParameters = queryParameters.set('tiempotext', <any>tiempotext);
        }
        if (distancia !== undefined && distancia !== null) {
            queryParameters = queryParameters.set('distancia', <any>distancia);
        }
        if (fechahorainicio !== undefined && fechahorainicio !== null) {
            queryParameters = queryParameters.set('fechahorainicio', <any>fechahorainicio);
        }
        if (fechahorallegada !== undefined && fechahorallegada !== null) {
            queryParameters = queryParameters.set('fechahorallegada', <any>fechahorallegada);
        }
        if (clientevaloracion !== undefined && clientevaloracion !== null) {
            queryParameters = queryParameters.set('clientevaloracion', <any>clientevaloracion);
        }
        if (clientecomentario !== undefined && clientecomentario !== null) {
            queryParameters = queryParameters.set('clientecomentario', <any>clientecomentario);
        }
        if (drivervaloracion !== undefined && drivervaloracion !== null) {
            queryParameters = queryParameters.set('drivervaloracion', <any>drivervaloracion);
        }
        if (drivercomentario !== undefined && drivercomentario !== null) {
            queryParameters = queryParameters.set('drivercomentario', <any>drivercomentario);
        }
        if (notificado !== undefined && notificado !== null) {
            queryParameters = queryParameters.set('notificado', <any>notificado);
        }
        if (costoentrega !== undefined && costoentrega !== null) {
            queryParameters = queryParameters.set('costoentrega', <any>costoentrega);
        }
        if (costototal !== undefined && costototal !== null) {
            queryParameters = queryParameters.set('costototal', <any>costototal);
        }
        if (metodopago !== undefined && metodopago !== null) {
            queryParameters = queryParameters.set('metodopago', <any>metodopago);
        }
        if (fecharegistro !== undefined && fecharegistro !== null) {
            queryParameters = queryParameters.set('fecharegistro', <any>fecharegistro);
        }

        let headers = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<any>(`${this.basePath}/app_servicios`,
            appServicios,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param appServicios app_servicios
     * @param select Filtering Columns
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appServiciosPost(appServicios?: AppServicios, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appServiciosPost(appServicios?: AppServicios, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appServiciosPost(appServicios?: AppServicios, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appServiciosPost(appServicios?: AppServicios, select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (select !== undefined && select !== null) {
            queryParameters = queryParameters.set('select', <any>select);
        }

        let headers = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            headers = headers.set('Prefer', String(prefer));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/app_servicios`,
            appServicios,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
